name: generate metrics

on:
  schedule:
    - cron: "*/30 * * * *" 
  
  workflow_dispatch:
  
  push:
    branches:
    - main
    
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
      
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.achievements.detailed.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: X
          
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.achievements.compact.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: X

      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.habits.facts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          from: 1000
          plugin_habits_days: 30
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          plugin_habits_trim: yes
          config_timezone: Europe/Paris

      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.habits.charts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          from: 1000
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugin_habits_trim: yes
          config_timezone: Europe/Paris

      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

