name: generate metrics

on:
  schedule:
    - cron: "*/30 * * * *" 
  
  workflow_dispatch:
  
  push:
    branches:
    - main
    
jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: generate metrics
        uses: lowlighter/metrics@65836723097537a54cd8eb90f61839426b4266b6
        with:
          base: <default-value>
