name: generate metrics

on:
  schedule:
    - cron: "*/30 * * * *" 
  
  workflow_dispatch:
  
  push:
    branches:
    - main
    
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
